/**
 * Build script to inject environment variables into env-config.js
 * This allows us to use Vercel environment variables while keeping the code secure
 * 
 * Usage:
 *   - Local: Create .env file with OPENAI_API_KEY=your_key
 *   - Vercel: Set OPENAI_API_KEY in Vercel dashboard
 */

const fs = require('fs');
const path = require('path');

// Try to load dotenv for local development (won't break if not installed)
try {
    require('dotenv').config();
} catch (e) {
    // dotenv not installed, that's okay for Vercel builds
}

// Get OpenAI API key from environment variable
const openaiKey = process.env.OPENAI_API_KEY || '';

// Escape the key for JavaScript string (handle quotes and backslashes)
const escapedKey = openaiKey.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');

// Create env-config.js file that will be loaded before config.js
const envConfigContent = `// Environment variables injected at build time
// This file is generated by build.js - DO NOT EDIT MANUALLY
// The OPENAI_API_KEY is injected from process.env.OPENAI_API_KEY during build
window.OPENAI_API_KEY_ENV = ${openaiKey ? `'${escapedKey}'` : "''"};

// Log for debugging (only in development)
if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    console.log('🔑 OpenAI API Key loaded from environment:', openaiKey ? '✅ Set' : '❌ Not set');
}
`;

const envConfigPath = path.join(__dirname, 'src', 'env-config.js');
fs.writeFileSync(envConfigPath, envConfigContent, 'utf8');

console.log('✅ Build complete: Environment variables injected');
if (openaiKey) {
    console.log('✅ OpenAI API key found and injected (length: ' + openaiKey.length + ' chars)');
} else {
    console.log('⚠️  Warning: OPENAI_API_KEY not set in environment');
    console.log('   Set it in Vercel dashboard or create .env file for local development');
}
