/**
 * Build script to inject environment variables and prepare files for Vercel
 * This allows us to use Vercel environment variables while keeping the code secure
 * 
 * Usage:
 *   - Local: Create .env file with OPENAI_API_KEY=your_key
 *   - Vercel: Set OPENAI_API_KEY in Vercel dashboard
 */

const fs = require('fs');
const path = require('path');

// Try to load dotenv for local development (won't break if not installed)
try {
    require('dotenv').config();
} catch (e) {
    // dotenv not installed, that's okay for Vercel builds
}

// Get OpenAI API key from environment variable
const openaiKey = process.env.OPENAI_API_KEY || '';

// Escape the key for JavaScript string (handle quotes and backslashes)
const escapedKey = openaiKey.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');

// Create env-config.js file that will be loaded before config.js
const envConfigContent = `// Environment variables injected at build time
// This file is generated by build.js - DO NOT EDIT MANUALLY
// The OPENAI_API_KEY is injected from process.env.OPENAI_API_KEY during build
window.OPENAI_API_KEY_ENV = ${openaiKey ? `'${escapedKey}'` : "''"};

// Log for debugging (only in development)
if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    console.log('🔑 OpenAI API Key loaded from environment:', openaiKey ? '✅ Set' : '❌ Not set');
}
`;

const envConfigPath = path.join(__dirname, 'src', 'env-config.js');
fs.writeFileSync(envConfigPath, envConfigContent, 'utf8');

// For Vercel: Create public directory and copy all necessary files
const publicDir = path.join(__dirname, 'public');
if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
}

// Function to copy directory recursively
function copyDir(src, dest) {
    if (!fs.existsSync(dest)) {
        fs.mkdirSync(dest, { recursive: true });
    }
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);
        if (entry.isDirectory()) {
            copyDir(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

// Copy all necessary files and directories to public
const filesToCopy = [
    'src',
    'assets',
    'manifest.xml',
    'package.json'
];

for (const item of filesToCopy) {
    const srcPath = path.join(__dirname, item);
    const destPath = path.join(publicDir, item);
    if (fs.existsSync(srcPath)) {
        const stat = fs.statSync(srcPath);
        if (stat.isDirectory()) {
            copyDir(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

console.log('✅ Build complete: Environment variables injected');
console.log('✅ Files copied to public directory for Vercel');
if (openaiKey) {
    console.log('✅ OpenAI API key found and injected (length: ' + openaiKey.length + ' chars)');
} else {
    console.log('⚠️  Warning: OPENAI_API_KEY not set in environment');
    console.log('   Set it in Vercel dashboard or create .env file for local development');
}
