/**
 * Build script to inject environment variables and prepare files for Vercel
 * This allows us to use Vercel environment variables while keeping the code secure
 * 
 * Usage:
 *   - Local: Create .env file with OPENAI_API_KEY=your_key
 *   - Vercel: Set OPENAI_API_KEY in Vercel dashboard
 */

const fs = require('fs');
const path = require('path');

// Try to load dotenv for local development (won't break if not installed)
try {
    require('dotenv').config();
} catch (e) {
    // dotenv not installed, that's okay for Vercel builds
}

// Get OpenAI API key from environment variable
const openaiKey = process.env.OPENAI_API_KEY || '';

// Escape the key for JavaScript string (handle quotes and backslashes)
const escapedKey = openaiKey.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');

// Create env-config.js file that will be loaded before config.js
const envConfigContent = `// Environment variables injected at build time
// This file is generated by build.js - DO NOT EDIT MANUALLY
// The OPENAI_API_KEY is injected from process.env.OPENAI_API_KEY during build
window.OPENAI_API_KEY_ENV = ${openaiKey ? `'${escapedKey}'` : "''"};

// Log for debugging (only in development)
if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    console.log('🔑 OpenAI API Key loaded from environment:', window.OPENAI_API_KEY_ENV ? '✅ Set' : '❌ Not set');
}
`;

const envConfigPath = path.join(__dirname, 'src', 'env-config.js');
fs.writeFileSync(envConfigPath, envConfigContent, 'utf8');

// For Vercel: Create public directory and copy all necessary files
const publicDir = path.join(__dirname, 'public');
if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
}

// Function to copy directory recursively
function copyDir(src, dest) {
    if (!fs.existsSync(dest)) {
        fs.mkdirSync(dest, { recursive: true });
    }
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);
        if (entry.isDirectory()) {
            copyDir(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

// Create index.html for root access
const indexHtmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Outlook Procurement Add-in</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            max-width: 800px;
            margin: 100px auto;
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }
        h1 {
            color: #0078d4;
        }
        .info-box {
            background: #f3f2f1;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .status {
            display: inline-block;
            padding: 4px 12px;
            background: #107c10;
            color: white;
            border-radius: 4px;
            font-size: 14px;
            font-weight: bold;
        }
        code {
            background: #f3f2f1;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
        }
    </style>
</head>
<body>
    <h1>Outlook Procurement Workflow Add-in</h1>
    
    <div class="info-box">
        <p><span class="status">✓ DEPLOYED</span></p>
        <p>This is the deployment server for the Outlook Procurement Add-in.</p>
    </div>

    <h2>Add-in Information</h2>
    <ul>
        <li><strong>Main Taskpane:</strong> <a href="/src/taskpane/taskpane.html">/src/taskpane/taskpane.html</a></li>
        <li><strong>Manifest:</strong> <a href="/manifest.xml">/manifest.xml</a></li>
    </ul>

    <h2>How to Use</h2>
    <p>This add-in is designed to be loaded within Microsoft Outlook. To use it:</p>
    <ol>
        <li>Download the <code>manifest.xml</code> file</li>
        <li>In Outlook, go to <strong>Get Add-ins</strong> → <strong>My add-ins</strong> → <strong>Add a custom add-in</strong></li>
        <li>Select the manifest.xml file</li>
        <li>The manifest should point to this deployment URL</li>
    </ol>

    <p><em>Note: The manifest.xml file needs to be updated with this deployment URL instead of localhost.</em></p>
</body>
</html>`;

// Copy all necessary files and directories to public
const filesToCopy = [
    'src',
    'assets',
    'manifest.xml',
    'package.json'
];

for (const item of filesToCopy) {
    const srcPath = path.join(__dirname, item);
    const destPath = path.join(publicDir, item);
    if (fs.existsSync(srcPath)) {
        const stat = fs.statSync(srcPath);
        if (stat.isDirectory()) {
            copyDir(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

// Create index.html in public directory
const indexHtmlPath = path.join(publicDir, 'index.html');
fs.writeFileSync(indexHtmlPath, indexHtmlContent, 'utf8');

// Verify critical assets are present
const criticalAssets = [
    'assets/hexa-logo-2.png',
    'assets/hexa-logo.png',
    'assets/attachments/RFQ_Template.pdf',
    'assets/attachments/Terms_Conditions.pdf'
];

console.log('\n📦 Verifying critical assets...');
let allAssetsPresent = true;
for (const asset of criticalAssets) {
    const assetPath = path.join(publicDir, asset);
    if (fs.existsSync(assetPath)) {
        const stats = fs.statSync(assetPath);
        console.log(`✅ ${asset} (${(stats.size / 1024).toFixed(2)} KB)`);
    } else {
        console.log(`❌ MISSING: ${asset}`);
        allAssetsPresent = false;
    }
}

if (!allAssetsPresent) {
    console.log('\n⚠️  WARNING: Some critical assets are missing!');
    console.log('   Make sure all files in the assets folder are committed to git.');
}

console.log('\n✅ Build complete: Environment variables injected');
console.log('✅ Files copied to public directory for Vercel');
if (openaiKey) {
    console.log('✅ OpenAI API key found and injected (length: ' + openaiKey.length + ' chars)');
} else {
    console.log('⚠️  Warning: OPENAI_API_KEY not set in environment');
    console.log('   Set it in Vercel dashboard or create .env file for local development');
}
